import { useState } from 'react'
import jsPDF from 'jspdf'

function Report({ onBack }) {
  const [generating, setGenerating] = useState(false)
  const [generated, setGenerated] = useState(false)

  const sessions = JSON.parse(localStorage.getItem('wageshield_sessions') || '[]')
  const payments = JSON.parse(localStorage.getItem('wageshield_payments') || '[]')

  const totalUnpaid = payments
    .reduce((sum, p) => sum + Math.max(0, parseFloat(p.gap || 0)), 0)
    .toFixed(2)

  const unpaidCount = payments.filter(p => parseFloat(p.gap) > 0).length

  const generatePDF = () => {
    setGenerating(true)

    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()

    // Header
    doc.setFillColor(0, 230, 118)
    doc.rect(0, 0, pageWidth, 40, 'F')
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(22)
    doc.setFont('helvetica', 'bold')
    doc.text('WAGESHIELD', 20, 20)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')
    doc.text('Wage Protection Evidence Report', 20, 30)

    // Report info
    doc.setTextColor(50, 50, 50)
    doc.setFontSize(10)
    doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 52)
    doc.text(`Report ID: WS-${Date.now()}`, 20, 60)

    // Summary box
    doc.setFillColor(240, 240, 240)
    doc.rect(15, 68, pageWidth - 30, 30, 'F')
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(200, 0, 0)
    doc.text(`Total Unpaid Wages: $${totalUnpaid}`, 20, 80)
    doc.setTextColor(50, 50, 50)
    doc.setFont('helvetica', 'normal')
    doc.text(`Work Sessions Logged: ${sessions.length}   |   Payment Records: ${payments.length}   |   Violations: ${unpaidCount}`, 20, 90)

    let y = 110

    // Payment records
    if (payments.length > 0) {
      doc.setFontSize(13)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(0, 0, 0)
      doc.text('PAYMENT RECORDS', 20, y)
      y += 8

      doc.setDrawColor(0, 230, 118)
      doc.setLineWidth(0.5)
      doc.line(20, y, pageWidth - 20, y)
      y += 8

      payments.forEach((p, i) => {
        if (y > 260) {
          doc.addPage()
          y = 20
        }
        doc.setFontSize(10)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(0, 0, 0)
        doc.text(`${i + 1}. ${p.date} — ${p.employer || 'Unknown employer'}`, 20, y)
        y += 6
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(80, 80, 80)
        doc.text(`Hours: ${p.hoursWorked}h  |  Rate: $${p.hourlyRate}/hr  |  Expected: $${p.expectedPay}  |  Received: $${p.amountReceived}`, 25, y)
        y += 6
        if (parseFloat(p.gap) > 0) {
          doc.setTextColor(200, 0, 0)
          doc.setFont('helvetica', 'bold')
          doc.text(`⚠ UNDERPAID BY $${p.gap}`, 25, y)
        } else {
          doc.setTextColor(0, 150, 80)
          doc.text('✓ Paid in full', 25, y)
        }
        if (p.notes) {
          y += 6
          doc.setTextColor(100, 100, 100)
          doc.setFont('helvetica', 'normal')
          doc.text(`Notes: ${p.notes}`, 25, y)
        }
        y += 10
      })
    }

    // Work sessions
    if (sessions.length > 0) {
      if (y > 240) { doc.addPage(); y = 20 }
      y += 4
      doc.setFontSize(13)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(0, 0, 0)
      doc.text('WORK SESSIONS', 20, y)
      y += 8
      doc.setDrawColor(0, 230, 118)
      doc.line(20, y, pageWidth - 20, y)
      y += 8

      sessions.forEach((s, i) => {
        if (y > 270) { doc.addPage(); y = 20 }
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(60, 60, 60)
        doc.text(`${i + 1}. ${s.date}  |  ${s.clockIn} → ${s.clockOut}  |  Duration: ${s.duration}`, 20, y)
        y += 8
      })
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text('This report was generated by WageShield. Worker data is stored locally and never shared.', 20, 285)
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 30, 285)
    }

    doc.save(`WageShield_Report_${new Date().toISOString().split('T')[0]}.pdf`)
    setGenerating(false)
    setGenerated(true)
  }

  return (
    <div style={{
      maxWidth: '430px', margin: '0 auto', minHeight: '100vh',
      backgroundColor: '#0a0a0a', color: '#ffffff',
      fontFamily: 'system-ui, sans-serif', display: 'flex', flexDirection: 'column',
    }}>
      {/* Header */}
      <div style={{ padding: '20px 24px 16px', borderBottom: '1px solid #1a1a1a', display: 'flex', alignItems: 'center', gap: '12px' }}>
        <span onClick={onBack} style={{ cursor: 'pointer', color: '#00e676', fontSize: '20px' }}>←</span>
        <div>
          <div style={{ fontSize: '18px', fontWeight: '700', color: '#00e676' }}>Evidence Report</div>
          <div style={{ fontSize: '12px', color: '#666' }}>Generate your legal PDF</div>
        </div>
      </div>

      <div style={{ flex: 1, padding: '24px' }}>

        {/* Summary cards */}
        <div style={{ display: 'flex', gap: '12px', marginBottom: '24px' }}>
          <div style={{ flex: 1, backgroundColor: '#111', borderRadius: '12px', padding: '16px', border: '1px solid #1e1e1e' }}>
            <div style={{ fontSize: '12px', color: '#666', marginBottom: '4px' }}>Work sessions</div>
            <div style={{ fontSize: '24px', fontWeight: '700', color: '#00e676' }}>{sessions.length}</div>
          </div>
          <div style={{ flex: 1, backgroundColor: '#111', borderRadius: '12px', padding: '16px', border: '1px solid #1e1e1e' }}>
            <div style={{ fontSize: '12px', color: '#666', marginBottom: '4px' }}>Total unpaid</div>
            <div style={{ fontSize: '24px', fontWeight: '700', color: totalUnpaid > 0 ? '#ff4444' : '#00e676' }}>${totalUnpaid}</div>
          </div>
        </div>

        {/* What's included */}
        <div style={{ backgroundColor: '#111', borderRadius: '16px', padding: '20px', border: '1px solid #1e1e1e', marginBottom: '24px' }}>
          <div style={{ fontSize: '14px', fontWeight: '600', marginBottom: '14px' }}>Your report will include</div>
          {[
            `${sessions.length} work sessions with timestamps`,
            `${payments.length} payment records`,
            `${unpaidCount} wage violation${unpaidCount !== 1 ? 's' : ''} flagged`,
            'Total unpaid wages calculated',
            'Ready to send to a lawyer or labor board',
          ].map((item) => (
            <div key={item} style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px' }}>
              <span style={{ color: '#00e676', fontSize: '14px' }}>✓</span>
              <span style={{ fontSize: '14px', color: '#aaa' }}>{item}</span>
            </div>
          ))}
        </div>

        {/* Generate button */}
        <button onClick={generatePDF} disabled={generating} style={{
          width: '100%', padding: '18px', borderRadius: '12px', border: 'none',
          backgroundColor: generating ? '#333' : '#00e676',
          color: generating ? '#666' : '#000',
          fontSize: '16px', fontWeight: '700', cursor: generating ? 'not-allowed' : 'pointer',
          marginBottom: '12px'
        }}>
          {generating ? 'Generating...' : '📋 Generate PDF Report'}
        </button>

        {generated && (
          <div style={{ backgroundColor: '#0a2a1a', borderRadius: '12px', padding: '16px', border: '1px solid #00e676', textAlign: 'center' }}>
            <div style={{ fontSize: '20px', marginBottom: '6px' }}>✅</div>
            <div style={{ fontSize: '14px', color: '#00e676', fontWeight: '600' }}>Report downloaded!</div>
            <div style={{ fontSize: '12px', color: '#666', marginTop: '4px' }}>Check your Downloads folder</div>
          </div>
        )}

      </div>
    </div>
  )
}

export default Report